import{afterEach,describe,expect,test}from'bun:test';import{mkdtempSync,rmSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';
import{BankingLoanStore}from'./banking-loans.js';import type{InstitutionSettlementRecord}from'./institution-settlement-orchestrator.js';
const dirs:string[]=[];afterEach(()=>{for(const d of dirs.splice(0))rmSync(d,{recursive:true,force:true})});
const at='2026-01-01T00:00:00.000Z';function receipt(kind:string,amountGp:number,n:string):InstitutionSettlementRecord{return{domain:'banking',eventId:`loan.event.${n}`,eventKind:kind,sourceRef:`loan:${n}`,eventDigest:n.repeat(64),verifiedAt:at,settlementId:`${n.repeat(8)}-${n.repeat(4)}-4${n.repeat(3)}-8${n.repeat(3)}-${n.repeat(12)}`,reservationId:`loan.${n}`,payerKind:'business',payerActorId:kind==='loan-disbursed'?'bank':'forge',payeeKind:'business',payeeActorId:kind==='loan-disbursed'?'forge':'bank',amountGp,status:'committed',createdAt:at,updatedAt:at}}
describe('bank loans',()=>{test('disburses, accrues deterministic interest, becomes overdue and repays interest first',()=>{const root=mkdtempSync(join(tmpdir(),'loans-'));dirs.push(root);const s=new BankingLoanStore(join(root,'db.sqlite'));
    s.create({loanId:'forge-loan',bankId:'varrock',bankTreasuryActorId:'bank',borrowerKind:'business',borrowerActorId:'forge',principalGp:36500,annualInterestBps:1000,termDays:30},at);
    s.disburse('forge-loan',receipt('loan-disbursed',36500,'1'));const overdue=s.accrue('forge-loan','2026-02-10T00:00:00.000Z');expect(overdue).toMatchObject({interestOutstandingGp:400,status:'overdue'});
    const partial=s.repay('forge-loan',receipt('repayment-cleared',500,'2'),'2026-02-10T00:00:00.000Z');expect(partial).toMatchObject({interestOutstandingGp:0,principalOutstandingGp:36400,status:'overdue'});
    const done=s.repay('forge-loan',receipt('repayment-cleared',36400,'3'),'2026-02-10T00:00:00.000Z');expect(done.status).toBe('repaid');s.close()});
 test('rejects mismatched disbursement and overpayment',()=>{const root=mkdtempSync(join(tmpdir(),'loans-'));dirs.push(root);const s=new BankingLoanStore(join(root,'db.sqlite'));s.create({loanId:'loan-2',bankId:'varrock',bankTreasuryActorId:'bank',borrowerKind:'business',borrowerActorId:'forge',principalGp:100,annualInterestBps:0,termDays:10},at);
    expect(()=>s.disburse('loan-2',receipt('loan-disbursed',99,'4'))).toThrow('does not match');const paid=receipt('loan-disbursed',100,'5');s.disburse('loan-2',paid);s.disburse('loan-2',paid);
    expect(()=>s.disburse('loan-2',{...paid,eventDigest:'f'.repeat(64)})).toThrow('changed after posting');expect(()=>s.repay('loan-2',receipt('repayment-cleared',101,'6'),at)).toThrow('exceeds');s.close()});
 test('recognizes an exact repayment replay before accruing more interest',()=>{const root=mkdtempSync(join(tmpdir(),'loans-'));dirs.push(root);const s=new BankingLoanStore(join(root,'db.sqlite'));s.create({loanId:'loan-3',bankId:'varrock',bankTreasuryActorId:'bank',borrowerKind:'business',borrowerActorId:'forge',principalGp:36500,annualInterestBps:1000,termDays:300},at);s.disburse('loan-3',receipt('loan-disbursed',36500,'7'));const repayment=receipt('repayment-cleared',100,'8');const first=s.repay('loan-3',repayment,'2026-01-11T00:00:00.000Z');const replay=s.repay('loan-3',repayment,'2026-02-11T00:00:00.000Z');expect(replay).toEqual(first);s.close()})});
