import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';

const adminDir = dirname(fileURLToPath(import.meta.url));

export const repoRoot = resolve(adminDir, '../../..');
export const botsDir = join(repoRoot, 'bots');
export const playerSavesDir = join(repoRoot, 'server', 'engine', 'data', 'players', 'main');
export const webclientDir = join(repoRoot, 'server', 'webclient');
export const adminPublicDir = join(adminDir, 'public');
export const adminLocalDir = join(repoRoot, '.local', 'admin');
export const adminLogsDir = join(adminLocalDir, 'logs');
export const adminSkillLogsDir = join(adminLocalDir, 'skill-logs');
export const adminTrashDir = join(adminLocalDir, 'trash');
export const activeSkillsDir = join(adminLocalDir, 'active-skills');
export const skillRunsDir = join(repoRoot, '.local', 'agent-skills', 'runs');
export const auditLogPath = join(adminLocalDir, 'audit.jsonl');
export const economyLogPath = join(adminLocalDir, 'economy.jsonl');
export const experimentsDir = join(adminLocalDir, 'experiments');
export const worldModManifestPath = join(repoRoot, 'config', 'world-mods.json');
export const worldModStatePath = join(adminLocalDir, 'world-mod-state.json');
export const worldModBackupsDir = join(adminLocalDir, 'world-mod-backups');
export const agentStateDbPath = join(repoRoot, '.local', 'agent-state', 'agents.sqlite');
export const llmRuntimeConfigPath = join(repoRoot, 'config', 'llm-runtime.json');
export const llmRuntimeOverridePath = join(adminLocalDir, 'llm-runtime.json');
export const llmApiKeyPath = join(adminLocalDir, 'secrets', 'openai-api-key.txt');
export const llmAuditLogPath = join(adminLocalDir, 'llm-audit.jsonl');
export const llmReplanLogPath = join(adminLocalDir, 'llm-replans.jsonl');
export const capabilityGapsPath = join(repoRoot, '.local', 'agent-skills', 'capability-gaps.json');
export const skillBuilderLedgerPath = join(adminLocalDir, 'skill-builder.jsonl');
export const skillTrialsPath = join(repoRoot, '.local', 'agent-skills', 'trials.json');
export const skillVerificationsDir = join(repoRoot, '.local', 'agent-skills', 'verifications');
export const agentSkillsLocalDir = join(repoRoot, '.local', 'agent-skills');
export const skillLearningPath = join(agentSkillsLocalDir, 'learning.json');
export const policySkillsDir = join(agentSkillsLocalDir, 'policy-catalog');
